// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/csgofloat/items': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/csgofloat/items.get').default>>>>
    }
    '/api/csgofloat/price/:name': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/csgofloat/price/[name].get').default>>>>
    }
    '/api/upgrade/perform': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upgrade/perform.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}